# Generated by Django 4.2.11 on 2025-08-06 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('sim_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField()),
                ('html_plot', models.TextField()),
                ('data', models.BinaryField()),
            ],
        ),
    ]
