# Generated by Django 4.2.11 on 2025-08-06 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lattice_size', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('impurity_concentration', models.FloatField()),
                ('diffusion_x', models.FloatField()),
                ('diffusion_y', models.FloatField()),
                ('diffusion_z', models.FloatField()),
                ('impurity_effect', models.FloatField()),
                ('flux', models.FloatField()),
                ('run_sweep', models.BooleanField(default=False)),
                ('simulation_data', models.BinaryField()),
                ('html_plot', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
    ]
