# Generated by Django 4.2.11 on 2025-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_savedsimulation_delete_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsimulation',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the simulation', max_length=100, null=True),
        ),
    ]
