# Generated by Django 4.2.11 on 2025-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_savedsimulation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsimulation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedsimulation',
            name='comparison_plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedsimulation',
            name='html_plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedsimulation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
